language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qxDMJfy+XBjKzk1rW3TzTj+W5rY0LjW+0VtuiDf2G/yxAPbPK9OeKdLCwnsqIk/RZdEEi8OHxmibAD22uD4kUq6E3rMDQOYOgC/NU04vNkpfY84kM+6+3r0ANgEaynKLo0HdUOQKRiz1LV3VRFb8ZKwhxHFm/dgrIVSEgYzNELTSqrF20pocB79l+gnsyMQeq4zA+4/boCnmaBmdqMBd5GunTpdN3fbXTbIkr7enGMy5QYvYBkATn7D+p0PgYohjlJN2as7cawCQzkvLxUme8yA3Y+suUsspOSuifmxH4/FX8Xgq1cLgbTTzeH7KJlJq6KlCAr/6MlNHoSb/eXK8k03S9cigIrYgBTs7D1hLQJ5S5A3lRLd0/RY55eiQlF/5dfcaIYgBQLwWn2To0WP+UwkKotvJ7zVSMmA8NAPaexNPYY98/xTefKoGHBZflyNxKlr2bxcQeuvV3a/xiC9VxObRmCyAOrjig8HyATVd+4PeqZtr02ZeXTBYOW+ciCZJpi0tlEH5Hv9l5JLLu9vykXmlsx30IyX7usEZtIe7PkjlRkpq98jSdUziNtRf+uZs2riUesHkbA7BNO5XMMxazliOgo8K5o+QXC9F9fQfJITBBFaRZ0zssSu77LNIMrGrUZQeXPa8TJICde+x+b7sqCK4eNGApIQPRYc81AadUsk=
  file:
    - 'hast-util-interactive.js'
    - 'hast-util-interactive.min.js'
  on:
    tags: true
